import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/nextAuth';
import { LoginButton, LogoutButton } from '@/components';
import { AiFillGithub } from 'react-icons/ai';
import { IoIosMail } from 'react-icons/io';
import { HiDevicePhoneMobile } from 'react-icons/hi2';
import { SiVelog } from 'react-icons/si';
import AuthProvider from '@/components/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children, modal }: { children: React.ReactNode; modal: React.ReactNode }) => {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="border-b-2 border-zinc-950">
          <div className="container mx-auto my-0 p-4 flex justify-between ">
            <Link href="/">
              <h1 className="text-3xl font-bold">TodoList</h1>
            </Link>
            <div className="flex space-x-5 items-center">
              {session ? (
                <>
                  <Link href="/todos" className="font-bold hover:text-gray-600">
                    My Todos
                  </Link>
                  <LogoutButton />
                </>
              ) : (
                <LoginButton />
              )}
            </div>
          </div>
        </nav>
        <AuthProvider>
          <main>
            {children}
            {modal}
          </main>
        </AuthProvider>
        <footer className="w-full mt-32 bottom-0 border-t-2 border-zinc-950">
          <div className="container flex justify-between space-x-4 mx-auto my-0 p-4">
            <div>
              <p className="font-bold">Seo Jun Pyo</p>
              <p className="text-sm flex space-x-1 items-center">
                <span>
                  <IoIosMail />
                </span>
                <span>cooljp95@naver.com</span>
              </p>
              <p className="text-sm flex space-x-1 items-center">
                <span>
                  <HiDevicePhoneMobile />
                </span>
                <span>010-2395-9282</span>
              </p>
            </div>
            <div className="flex space-x-4 text-2xl items-center">
              <Link href="https://github.com/seoJunPyo">
                <AiFillGithub />
              </Link>
              <Link href="https://velog.io/@cooljp95">
                <SiVelog />
              </Link>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
};

export default RootLayout;
